{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "df = pd.read_parquet('yellow_tripdata_2023-01.parquet')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "from sqlalchemy import create_engine\n",
    "engine = create_engine('postgresql://root:root@localhost:5432/ny_data')\n",
    "engine_postgre = engine.connect()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "ename": "ProgrammingError",
     "evalue": "(psycopg2.errors.DuplicateTable) relation \"ny_yellow_taxi\" already exists\n\n[SQL: \nCREATE TABLE ny_yellow_taxi (\n\t\"VendorID\" BIGINT, \n\ttpep_pickup_datetime TIMESTAMP WITHOUT TIME ZONE, \n\ttpep_dropoff_datetime TIMESTAMP WITHOUT TIME ZONE, \n\tpassenger_count FLOAT(53), \n\ttrip_distance FLOAT(53), \n\t\"RatecodeID\" FLOAT(53), \n\tstore_and_fwd_flag TEXT, \n\t\"PULocationID\" BIGINT, \n\t\"DOLocationID\" BIGINT, \n\tpayment_type BIGINT, \n\tfare_amount FLOAT(53), \n\textra FLOAT(53), \n\tmta_tax FLOAT(53), \n\ttip_amount FLOAT(53), \n\ttolls_amount FLOAT(53), \n\timprovement_surcharge FLOAT(53), \n\ttotal_amount FLOAT(53), \n\tcongestion_surcharge FLOAT(53), \n\tairport_fee FLOAT(53)\n)\n\n]\n(Background on this error at: http://sqlalche.me/e/13/f405)",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mDuplicateTable\u001b[0m                            Traceback (most recent call last)",
      "File \u001b[1;32mc:\\Users\\Duncan.Pham\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sqlalchemy\\engine\\base.py:1276\u001b[0m, in \u001b[0;36mConnection._execute_context\u001b[1;34m(self, dialect, constructor, statement, parameters, *args)\u001b[0m\n\u001b[0;32m   1275\u001b[0m     \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m evt_handled:\n\u001b[1;32m-> 1276\u001b[0m         \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mdialect\u001b[39m.\u001b[39;49mdo_execute(\n\u001b[0;32m   1277\u001b[0m             cursor, statement, parameters, context\n\u001b[0;32m   1278\u001b[0m         )\n\u001b[0;32m   1280\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_has_events \u001b[39mor\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mengine\u001b[39m.\u001b[39m_has_events:\n",
      "File \u001b[1;32mc:\\Users\\Duncan.Pham\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sqlalchemy\\engine\\default.py:608\u001b[0m, in \u001b[0;36mDefaultDialect.do_execute\u001b[1;34m(self, cursor, statement, parameters, context)\u001b[0m\n\u001b[0;32m    607\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mdo_execute\u001b[39m(\u001b[39mself\u001b[39m, cursor, statement, parameters, context\u001b[39m=\u001b[39m\u001b[39mNone\u001b[39;00m):\n\u001b[1;32m--> 608\u001b[0m     cursor\u001b[39m.\u001b[39;49mexecute(statement, parameters)\n",
      "\u001b[1;31mDuplicateTable\u001b[0m: relation \"ny_yellow_taxi\" already exists\n",
      "\nThe above exception was the direct cause of the following exception:\n",
      "\u001b[1;31mProgrammingError\u001b[0m                          Traceback (most recent call last)",
      "\u001b[1;32md:\\airflow\\week1.ipynb Cell 3\u001b[0m in \u001b[0;36m2\n\u001b[0;32m      <a href='vscode-notebook-cell:/d%3A/airflow/week1.ipynb#W2sZmlsZQ%3D%3D?line=0'>1</a>\u001b[0m sql \u001b[39m=\u001b[39m pd\u001b[39m.\u001b[39mio\u001b[39m.\u001b[39msql\u001b[39m.\u001b[39mget_schema(df, \u001b[39m'\u001b[39m\u001b[39mny_yellow_taxi\u001b[39m\u001b[39m'\u001b[39m, con\u001b[39m=\u001b[39mengine)\n\u001b[1;32m----> <a href='vscode-notebook-cell:/d%3A/airflow/week1.ipynb#W2sZmlsZQ%3D%3D?line=1'>2</a>\u001b[0m engine\u001b[39m.\u001b[39;49mexecute(sql)\n",
      "File \u001b[1;32mc:\\Users\\Duncan.Pham\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sqlalchemy\\engine\\base.py:2235\u001b[0m, in \u001b[0;36mEngine.execute\u001b[1;34m(self, statement, *multiparams, **params)\u001b[0m\n\u001b[0;32m   2215\u001b[0m \u001b[39m\"\"\"Executes the given construct and returns a\u001b[39;00m\n\u001b[0;32m   2216\u001b[0m \u001b[39m:class:`_engine.ResultProxy`.\u001b[39;00m\n\u001b[0;32m   2217\u001b[0m \n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m   2231\u001b[0m \n\u001b[0;32m   2232\u001b[0m \u001b[39m\"\"\"\u001b[39;00m\n\u001b[0;32m   2234\u001b[0m connection \u001b[39m=\u001b[39m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_contextual_connect(close_with_result\u001b[39m=\u001b[39m\u001b[39mTrue\u001b[39;00m)\n\u001b[1;32m-> 2235\u001b[0m \u001b[39mreturn\u001b[39;00m connection\u001b[39m.\u001b[39mexecute(statement, \u001b[39m*\u001b[39mmultiparams, \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mparams)\n",
      "File \u001b[1;32mc:\\Users\\Duncan.Pham\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sqlalchemy\\engine\\base.py:1003\u001b[0m, in \u001b[0;36mConnection.execute\u001b[1;34m(self, object_, *multiparams, **params)\u001b[0m\n\u001b[0;32m    944\u001b[0m \u001b[39mr\u001b[39m\u001b[39m\"\"\"Executes a SQL statement construct and returns a\u001b[39;00m\n\u001b[0;32m    945\u001b[0m \u001b[39m:class:`_engine.ResultProxy`.\u001b[39;00m\n\u001b[0;32m    946\u001b[0m \n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m   1000\u001b[0m \n\u001b[0;32m   1001\u001b[0m \u001b[39m\"\"\"\u001b[39;00m\n\u001b[0;32m   1002\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39misinstance\u001b[39m(object_, util\u001b[39m.\u001b[39mstring_types[\u001b[39m0\u001b[39m]):\n\u001b[1;32m-> 1003\u001b[0m     \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_execute_text(object_, multiparams, params)\n\u001b[0;32m   1004\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m   1005\u001b[0m     meth \u001b[39m=\u001b[39m object_\u001b[39m.\u001b[39m_execute_on_connection\n",
      "File \u001b[1;32mc:\\Users\\Duncan.Pham\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sqlalchemy\\engine\\base.py:1172\u001b[0m, in \u001b[0;36mConnection._execute_text\u001b[1;34m(self, statement, multiparams, params)\u001b[0m\n\u001b[0;32m   1170\u001b[0m dialect \u001b[39m=\u001b[39m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mdialect\n\u001b[0;32m   1171\u001b[0m parameters \u001b[39m=\u001b[39m _distill_params(multiparams, params)\n\u001b[1;32m-> 1172\u001b[0m ret \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_execute_context(\n\u001b[0;32m   1173\u001b[0m     dialect,\n\u001b[0;32m   1174\u001b[0m     dialect\u001b[39m.\u001b[39;49mexecution_ctx_cls\u001b[39m.\u001b[39;49m_init_statement,\n\u001b[0;32m   1175\u001b[0m     statement,\n\u001b[0;32m   1176\u001b[0m     parameters,\n\u001b[0;32m   1177\u001b[0m     statement,\n\u001b[0;32m   1178\u001b[0m     parameters,\n\u001b[0;32m   1179\u001b[0m )\n\u001b[0;32m   1180\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_has_events \u001b[39mor\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mengine\u001b[39m.\u001b[39m_has_events:\n\u001b[0;32m   1181\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mdispatch\u001b[39m.\u001b[39mafter_execute(\n\u001b[0;32m   1182\u001b[0m         \u001b[39mself\u001b[39m, statement, multiparams, params, ret\n\u001b[0;32m   1183\u001b[0m     )\n",
      "File \u001b[1;32mc:\\Users\\Duncan.Pham\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sqlalchemy\\engine\\base.py:1316\u001b[0m, in \u001b[0;36mConnection._execute_context\u001b[1;34m(self, dialect, constructor, statement, parameters, *args)\u001b[0m\n\u001b[0;32m   1313\u001b[0m             result\u001b[39m.\u001b[39m_autoclose_connection \u001b[39m=\u001b[39m \u001b[39mTrue\u001b[39;00m\n\u001b[0;32m   1315\u001b[0m \u001b[39mexcept\u001b[39;00m \u001b[39mBaseException\u001b[39;00m \u001b[39mas\u001b[39;00m e:\n\u001b[1;32m-> 1316\u001b[0m     \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_handle_dbapi_exception(\n\u001b[0;32m   1317\u001b[0m         e, statement, parameters, cursor, context\n\u001b[0;32m   1318\u001b[0m     )\n\u001b[0;32m   1320\u001b[0m \u001b[39mreturn\u001b[39;00m result\n",
      "File \u001b[1;32mc:\\Users\\Duncan.Pham\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sqlalchemy\\engine\\base.py:1510\u001b[0m, in \u001b[0;36mConnection._handle_dbapi_exception\u001b[1;34m(self, e, statement, parameters, cursor, context)\u001b[0m\n\u001b[0;32m   1508\u001b[0m     util\u001b[39m.\u001b[39mraise_(newraise, with_traceback\u001b[39m=\u001b[39mexc_info[\u001b[39m2\u001b[39m], from_\u001b[39m=\u001b[39me)\n\u001b[0;32m   1509\u001b[0m \u001b[39melif\u001b[39;00m should_wrap:\n\u001b[1;32m-> 1510\u001b[0m     util\u001b[39m.\u001b[39;49mraise_(\n\u001b[0;32m   1511\u001b[0m         sqlalchemy_exception, with_traceback\u001b[39m=\u001b[39;49mexc_info[\u001b[39m2\u001b[39;49m], from_\u001b[39m=\u001b[39;49me\n\u001b[0;32m   1512\u001b[0m     )\n\u001b[0;32m   1513\u001b[0m \u001b[39melse\u001b[39;00m:\n\u001b[0;32m   1514\u001b[0m     util\u001b[39m.\u001b[39mraise_(exc_info[\u001b[39m1\u001b[39m], with_traceback\u001b[39m=\u001b[39mexc_info[\u001b[39m2\u001b[39m])\n",
      "File \u001b[1;32mc:\\Users\\Duncan.Pham\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sqlalchemy\\util\\compat.py:182\u001b[0m, in \u001b[0;36mraise_\u001b[1;34m(***failed resolving arguments***)\u001b[0m\n\u001b[0;32m    179\u001b[0m     exception\u001b[39m.\u001b[39m__cause__ \u001b[39m=\u001b[39m replace_context\n\u001b[0;32m    181\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[1;32m--> 182\u001b[0m     \u001b[39mraise\u001b[39;00m exception\n\u001b[0;32m    183\u001b[0m \u001b[39mfinally\u001b[39;00m:\n\u001b[0;32m    184\u001b[0m     \u001b[39m# credit to\u001b[39;00m\n\u001b[0;32m    185\u001b[0m     \u001b[39m# https://cosmicpercolator.com/2016/01/13/exception-leaks-in-python-2-and-3/\u001b[39;00m\n\u001b[0;32m    186\u001b[0m     \u001b[39m# as the __traceback__ object creates a cycle\u001b[39;00m\n\u001b[0;32m    187\u001b[0m     \u001b[39mdel\u001b[39;00m exception, replace_context, from_, with_traceback\n",
      "File \u001b[1;32mc:\\Users\\Duncan.Pham\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sqlalchemy\\engine\\base.py:1276\u001b[0m, in \u001b[0;36mConnection._execute_context\u001b[1;34m(self, dialect, constructor, statement, parameters, *args)\u001b[0m\n\u001b[0;32m   1274\u001b[0m                 \u001b[39mbreak\u001b[39;00m\n\u001b[0;32m   1275\u001b[0m     \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m evt_handled:\n\u001b[1;32m-> 1276\u001b[0m         \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mdialect\u001b[39m.\u001b[39;49mdo_execute(\n\u001b[0;32m   1277\u001b[0m             cursor, statement, parameters, context\n\u001b[0;32m   1278\u001b[0m         )\n\u001b[0;32m   1280\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_has_events \u001b[39mor\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mengine\u001b[39m.\u001b[39m_has_events:\n\u001b[0;32m   1281\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mdispatch\u001b[39m.\u001b[39mafter_cursor_execute(\n\u001b[0;32m   1282\u001b[0m         \u001b[39mself\u001b[39m,\n\u001b[0;32m   1283\u001b[0m         cursor,\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m   1287\u001b[0m         context\u001b[39m.\u001b[39mexecutemany,\n\u001b[0;32m   1288\u001b[0m     )\n",
      "File \u001b[1;32mc:\\Users\\Duncan.Pham\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sqlalchemy\\engine\\default.py:608\u001b[0m, in \u001b[0;36mDefaultDialect.do_execute\u001b[1;34m(self, cursor, statement, parameters, context)\u001b[0m\n\u001b[0;32m    607\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mdo_execute\u001b[39m(\u001b[39mself\u001b[39m, cursor, statement, parameters, context\u001b[39m=\u001b[39m\u001b[39mNone\u001b[39;00m):\n\u001b[1;32m--> 608\u001b[0m     cursor\u001b[39m.\u001b[39;49mexecute(statement, parameters)\n",
      "\u001b[1;31mProgrammingError\u001b[0m: (psycopg2.errors.DuplicateTable) relation \"ny_yellow_taxi\" already exists\n\n[SQL: \nCREATE TABLE ny_yellow_taxi (\n\t\"VendorID\" BIGINT, \n\ttpep_pickup_datetime TIMESTAMP WITHOUT TIME ZONE, \n\ttpep_dropoff_datetime TIMESTAMP WITHOUT TIME ZONE, \n\tpassenger_count FLOAT(53), \n\ttrip_distance FLOAT(53), \n\t\"RatecodeID\" FLOAT(53), \n\tstore_and_fwd_flag TEXT, \n\t\"PULocationID\" BIGINT, \n\t\"DOLocationID\" BIGINT, \n\tpayment_type BIGINT, \n\tfare_amount FLOAT(53), \n\textra FLOAT(53), \n\tmta_tax FLOAT(53), \n\ttip_amount FLOAT(53), \n\ttolls_amount FLOAT(53), \n\timprovement_surcharge FLOAT(53), \n\ttotal_amount FLOAT(53), \n\tcongestion_surcharge FLOAT(53), \n\tairport_fee FLOAT(53)\n)\n\n]\n(Background on this error at: http://sqlalche.me/e/13/f405)"
     ]
    }
   ],
   "source": [
    "sql = pd.io.sql.get_schema(df, 'ny_yellow_taxi', con=engine)\n",
    "engine.execute(sql)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "CPU times: total: 2min 1s\n",
      "Wall time: 5min 44s\n"
     ]
    }
   ],
   "source": [
    "%time df.to_sql(name='ny_yellow_taxi', if_exists='append', con=engine_postgre, index=False)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
